this.tree = new DialogTree();
this.tree.npcHeader = "Your first real assignment is to take out some of the Imperial Probe Droids that are constantly patrolling the planet trying to find us. Since you did so well with the Wampa feel free to take a T-47 Airspeeder if you'd like. It'll make things a lot faster, and its blasters will hit those Imperial Probe Droids a lot harder. Stop by the Quartermaster and he'll give you some Rebel Pilot Armor and a ship. I want you to bring me back at least 5 of those droids. Good luck, soldier.";
this.tree.response1 = "But I've never flown one of those before, sir!";
this.tree.response1DT = new DialogTree();
this.tree.response1DT.npcHeader = "I'm sure you'll figure it out quick enough, kid.";
this.tree.response2 = "They won't even know what hit 'em.";
this.tree.response2DT = new DialogTree();
this.tree.response3 = "Thank you sir, I'll make you proud.";
this.tree.response3DT = new DialogTree();
