using System;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;

namespace SchematicExporter
{
    internal class Exporter
    {
        /// <summary>
        /// Maximum blocks/lines per generation statement
        /// </summary>
        public const int MaxBlocksPerGen = 500;

        /// <summary>
        /// Exports the given schematic following the given export options
        /// </summary>
        /// <param name="options">The export options</param>
        /// <param name="schematic">The schematic to export</param>
        /// <returns>The number of chunks exported</returns>
        public static int Export(ExportOptions options, Schematic schematic)
        {
            var gen = new StringBuilder();
            var first = true;

            gen.AppendLine(HeaderComment());

            gen.AppendLine("if (this.locY == 0)");
            gen.AppendLine("\tthis.locY = (int)MathUtils.map(this.rootHeight, -2, 2, 0, 128);\n");

            var chunks = 0;

            for (var x = 0; x < schematic.Width; x += 16)
                for (var z = 0; z < schematic.Length; z += 16)
                {
                    var classTitle =
                        Utils.UpperFirst(string.Format(options.ClassName,
                            string.Format("_x{0}_z{1}", x, z)));

                    Console.Title = string.Format("SchematicExporter - Exporting {0}...", classTitle);
                    
                    ChunkExport.Export(options, schematic, x, z);

                    chunks++;

                    gen.AppendLine(string.Format("{0}if (chunkX == {1} && chunkZ == {2})", first ? "" : "else ", x, z));

                    gen.AppendLine(
                        string.Format("\tnew {0}().generate(world, chunkX, this.locY, chunkZ);",
                            classTitle));

                    first = false;
                }

            using (var w = new StreamWriter("output/" + options.Path + "/" + string.Format(options.FileName, "Generator")))
                w.WriteLine(gen);

            return chunks;
        }
    
        public static string HeaderComment()
        {
            var gen = new StringBuilder();

            gen.AppendLine("/*");
            gen.AppendLine(" * Generated by SchematicExporter");
            gen.AppendLine(string.Format(" * {0}", DateTime.Now));
            gen.Append(" */");

            return gen.ToString();
        }
    }
}
