// Date: 1/23/2016 8:10:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer bolt;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      bolt = new ModelRenderer(this, 0, 0);
      bolt.addBox(-0.5F, -0.5F, -8F, 1, 1, 16);
      bolt.setRotationPoint(0F, 0F, 0F);
      bolt.setTextureSize(64, 32);
      bolt.mirror = true;
      setRotation(bolt, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    bolt.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
