// Date: 8/2/2015 3:33:20 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer BunR;
    ModelRenderer BunL;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      BunR = new ModelRenderer(this, 0, 0);
      BunR.addBox(-1F, -2.5F, -2.5F, 2, 5, 5);
      BunR.setRotationPoint(-5F, -4F, 0F);
      BunR.setTextureSize(64, 32);
      BunR.mirror = true;
      setRotation(BunR, 0F, 0F, 0F);
      BunL = new ModelRenderer(this, 0, 11);
      BunL.addBox(-1F, -2.5F, -2.5F, 2, 5, 5);
      BunL.setRotationPoint(5F, -4F, 0F);
      BunL.setTextureSize(64, 32);
      BunL.mirror = true;
      setRotation(BunL, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    BunR.render(f5);
    BunL.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
