package com.parzivail.pswm.bank;

import com.parzivail.pswm.blocks.*;
import com.parzivail.pswm.blocks.hoth.*;
import com.parzivail.pswm.blocks.pipe.*;
import com.parzivail.util.basic.BasicBlock;
import com.parzivail.util.basic.BasicStairs;

/**
 * Created by colby on 12/18/2016.
 */
public class PBlocks
{
	public static BasicBlock infraBlack;
	public static BasicBlock infraCaution;
	public static BasicBlock infraCrate;
	public static BasicBlock infraDarkGray;
	public static BasicBlock infraDarkGrayLit;
	public static BasicBlock infraDarkGrayLit2;
	public static BasicBlock infraForest;
	public static BasicBlock infraForestInset;
	public static BasicBlock infraForestPanel1;
	public static BasicBlock infraForestPanel2;
	public static BasicBlock infraForestPanel3;
	public static BasicStairs infraForestStairs;
	public static BasicBlock infraForestVine;
	public static BasicBlock infraLight;
	public static BasicBlock infraLightinset;
	public static BasicBlock infraLightLit;
	public static BasicBlock infraLightFloorLit;
	public static BasicBlock infraGlass;
	public static BasicBlock infraPanel1;
	public static BasicBlock infraWhite;
	public static BasicBlock chromiumOre;
	public static BasicBlock cortosisOre;
	public static BasicBlock cortosisReverseOre;
	public static BasicBlock crystalBlack;
	public static BasicBlock crystalBlue;
	public static BasicBlock crystalCyan;
	public static BasicBlock crystalGray;
	public static BasicBlock crystalGreen;
	public static BasicBlock crystalPink;
	public static BasicBlock crystalPrism;
	public static BasicBlock crystalPurple;
	public static BasicBlock crystalWhite;
	public static BasicBlock crystalYellow;
	public static BasicBlock dagobahMud;
	public static BasicBlock diatiumOre;
	public static BasicBlock exoniumOre;
	public static BasicBlock focusingCrystalOre;
	public static BasicBlock hardpackSnow;
	public static BasicBlock heliciteOre;
	public static BasicBlock hothDoor;
	public static BasicBlock hothSnowCut;
	public static BasicBlock ilumStone;
	public static BasicBlock ioniteOre;
	public static BasicBlock keleriumOre;
	public static BasicBlock rubindumOre;
	public static BasicBlock spaceLamp;
	public static BasicBlock tatooineSand0;
	public static BasicBlock tatooineSand1;
	public static BasicBlock tatooineSandstoneBottom;
	public static BasicBlock tatooineSandstoneCarved;
	public static BasicBlock tatooineSandstoneNormal;
	public static BasicBlock tatooineSandstoneSmooth;
	public static BasicBlock tatooineSandstoneTop;
	public static BasicBlock templeStone;
	public static BasicBlock templeStoneBrick;
	public static BasicBlock templeStoneBrickFancy;
	public static BasicBlock templeStoneLit;
	public static BasicBlock templeStoneLitBrick;
	public static BasicBlock templeStoneLitBrickFancy;
	public static BasicBlock templeStoneLitSlabTop;
	public static BasicBlock templeStoneLitSlabTopDark;
	public static BasicBlock templeStoneSlabTop;
	public static BasicBlock templeStoneSlabTopDark;
	public static BasicBlock thorolideOre;
	public static BasicBlock titaniumChromiumBlock;
	public static BasicBlock titaniumOre;
	public static BasicBlock mudTable;
	public static BasicStairs mudStairs;
	public static BasicBlock fieldEmitter;
	public static BasicBlock holoTable;
	public static BasicBlock lightFence;

	public static BlockConsoleHoth1 consoleHoth1;
	public static BlockConsoleHothCurved1 consoleHothCurved1;
	public static BlockConsoleHothCurved2 consoleHothCurved2;
	public static BlockConsoleHothCurved3 consoleHothCurved3;
	public static BlockFloorLight floorLight;
	public static BlockFloorLight2 floorLight2;
	public static BlockHothCeilingLight hothCeilingLight;
	public static BlockHothCrate1 hothCrate1;
	public static BlockHothCrate2 hothCrate2;
	public static BlockMedicalConsole medicalConsole;
	public static BlockMedicalConsole2 medicalConsole2;
	public static BlockPipeDoubleOffsetBot pipeDoubleOffsetBot;
	public static BlockPipeDoubleOffsetBotSpecial pipeDoubleOffsetBotSpecial;
	public static BlockPipeDoubleOffsetTop pipeDoubleOffsetTop;
	public static BlockPipeDoubleOffsetTopSpecial pipeDoubleOffsetTopSpecial;
	public static BlockPipesClampedMass pipesClampedMass;
	public static BlockPipesMass pipesMass;
	public static BlockPipesSleevedMass pipesSleevedMass;
	public static BlockAncientJediStatue ancientJediStatue;
	public static BlockAntenna antenna;
	public static BlockBactaTank bactaTank;
	public static BlockBasket basket;
	public static BlockBlockTable blockTable;
	public static BlockCrateMass1 crateMass1;
	public static BlockCrateMosEspa crateMosEspa;
	public static BlockCrateVilla crateVilla;
	public static BlockCrystalCompressor crystalCompressor;
	public static BlockDeathStarDoor deathStarDoor;
	public static BlockDoorHoth doorHoth;
	public static BlockGenerator generator;
	public static BlockGirder girder;
	public static BlockGunRack gunRack;
	public static BlockHangingBucket hangingBucket;
	public static BlockHangingCauldron hangingCauldron;
	public static BlockHolotableMass holotableMass;
	public static BlockHothCeilingLight2 hothCeilingLight2;
	public static BlockHyperdriveBlock hyperdriveBlock;
	public static BlockLadder ladder;
	public static BlockLadderTop ladderTop;
	public static BlockLightsaberForge lightsaberForge;
	public static BlockMV mV;
	public static BlockMV2 mV2;
	public static BlockTarget target;
}
