import java.util.ArrayList;
import java.util.List;

public class BlockUtils
{
	public static List<BlockType> loadBlocks()
	{
		List<BlockType> ret = new ArrayList<BlockType>();
		ret.add(new BlockType(0, 0, "Air", "air"));
		ret.add(new BlockType(1, 0, "Stone", "stone"));
		ret.add(new BlockType(1, 1, "Granite", "stone"));
		ret.add(new BlockType(1, 2, "Polished Granite", "stone"));
		ret.add(new BlockType(1, 3, "Diorite", "stone"));
		ret.add(new BlockType(1, 4, "Polished Diorite", "stone"));
		ret.add(new BlockType(1, 5, "Andesite", "stone"));
		ret.add(new BlockType(1, 6, "Polished Andesite", "stone"));
		ret.add(new BlockType(2, 0, "Grass", "grass"));
		ret.add(new BlockType(3, 0, "Dirt", "dirt"));
		ret.add(new BlockType(3, 1, "Coarse Dirt", "dirt"));
		ret.add(new BlockType(3, 2, "Podzol", "dirt"));
		ret.add(new BlockType(4, 0, "Cobblestone", "cobblestone"));
		ret.add(new BlockType(5, 0, "Oak Wood Plank", "planks"));
		ret.add(new BlockType(5, 1, "Spruce Wood Plank", "planks"));
		ret.add(new BlockType(5, 2, "Birch Wood Plank", "planks"));
		ret.add(new BlockType(5, 3, "Jungle Wood Plank", "planks"));
		ret.add(new BlockType(5, 4, "Acacia Wood Plank", "planks"));
		ret.add(new BlockType(5, 5, "Dark Oak Wood Plank", "planks"));
		ret.add(new BlockType(6, 0, "Oak Sapling", "sapling"));
		ret.add(new BlockType(6, 1, "Spruce Sapling", "sapling"));
		ret.add(new BlockType(6, 2, "Birch Sapling", "sapling"));
		ret.add(new BlockType(6, 3, "Jungle Sapling", "sapling"));
		ret.add(new BlockType(6, 4, "Acacia Sapling", "sapling"));
		ret.add(new BlockType(6, 5, "Dark Oak Sapling", "sapling"));
		ret.add(new BlockType(7, 0, "Bedrock", "bedrock"));
		ret.add(new BlockType(8, 0, "Flowing Water", "flowing_water"));
		ret.add(new BlockType(9, 0, "Still Water", "water"));
		ret.add(new BlockType(10, 0, "Flowing Lava", "flowing_lava"));
		ret.add(new BlockType(11, 0, "Still Lava", "lava"));
		ret.add(new BlockType(12, 0, "Sand", "sand"));
		ret.add(new BlockType(12, 1, "Red Sand", "sand"));
		ret.add(new BlockType(13, 0, "Gravel", "gravel"));
		ret.add(new BlockType(14, 0, "Gold Ore", "gold_ore"));
		ret.add(new BlockType(15, 0, "Iron Ore", "iron_ore"));
		ret.add(new BlockType(16, 0, "Coal Ore", "coal_ore"));
		ret.add(new BlockType(17, 0, "Oak Wood", "log"));
		ret.add(new BlockType(17, 1, "Spruce Wood", "log"));
		ret.add(new BlockType(17, 2, "Birch Wood", "log"));
		ret.add(new BlockType(17, 3, "Jungle Wood", "log"));
		ret.add(new BlockType(18, 0, "Oak Leaves", "leaves"));
		ret.add(new BlockType(18, 1, "Spruce Leaves", "leaves"));
		ret.add(new BlockType(18, 2, "Birch Leaves", "leaves"));
		ret.add(new BlockType(18, 3, "Jungle Leaves", "leaves"));
		ret.add(new BlockType(19, 0, "Sponge", "sponge"));
		ret.add(new BlockType(19, 1, "Wet Sponge", "sponge"));
		ret.add(new BlockType(20, 0, "Glass", "glass"));
		ret.add(new BlockType(21, 0, "Lapis Lazuli Ore", "lapis_ore"));
		ret.add(new BlockType(22, 0, "Lapis Lazuli Block", "lapis_block"));
		ret.add(new BlockType(23, 0, "Dispenser", "dispenser"));
		ret.add(new BlockType(24, 0, "Sandstone", "sandstone"));
		ret.add(new BlockType(24, 1, "Chiseled Sandstone", "sandstone"));
		ret.add(new BlockType(24, 2, "Smooth Sandstone", "sandstone"));
		ret.add(new BlockType(25, 0, "Note Block", "noteblock"));
		ret.add(new BlockType(26, 0, "Bed", "bed"));
		ret.add(new BlockType(27, 0, "Powered Rail", "golden_rail"));
		ret.add(new BlockType(28, 0, "Detector Rail", "detector_rail"));
		ret.add(new BlockType(29, 0, "Sticky Piston", "sticky_piston"));
		ret.add(new BlockType(30, 0, "Cobweb", "web"));
		ret.add(new BlockType(31, 0, "Dead Shrub", "tallgrass"));
		ret.add(new BlockType(31, 1, "Grass", "tallgrass"));
		ret.add(new BlockType(31, 2, "Fern", "tallgrass"));
		ret.add(new BlockType(32, 0, "Dead Bush", "deadbush"));
		ret.add(new BlockType(33, 0, "Piston", "piston"));
		ret.add(new BlockType(34, 0, "Piston Head", "piston_head"));
		ret.add(new BlockType(35, 0, "White Wool", "wool"));
		ret.add(new BlockType(35, 1, "Orange Wool", "wool"));
		ret.add(new BlockType(35, 2, "Magenta Wool", "wool"));
		ret.add(new BlockType(35, 3, "Light Blue Wool", "wool"));
		ret.add(new BlockType(35, 4, "Yellow Wool", "wool"));
		ret.add(new BlockType(35, 5, "Lime Wool", "wool"));
		ret.add(new BlockType(35, 6, "Pink Wool", "wool"));
		ret.add(new BlockType(35, 7, "Gray Wool", "wool"));
		ret.add(new BlockType(35, 8, "Light Gray Wool", "wool"));
		ret.add(new BlockType(35, 9, "Cyan Wool", "wool"));
		ret.add(new BlockType(35, 10, "Purple Wool", "wool"));
		ret.add(new BlockType(35, 11, "Blue Wool", "wool"));
		ret.add(new BlockType(35, 12, "Brown Wool", "wool"));
		ret.add(new BlockType(35, 13, "Green Wool", "wool"));
		ret.add(new BlockType(35, 14, "Red Wool", "wool"));
		ret.add(new BlockType(35, 15, "Black Wool", "wool"));
		ret.add(new BlockType(37, 0, "Dandelion", "yellow_flower"));
		ret.add(new BlockType(38, 0, "Poppy", "red_flower"));
		ret.add(new BlockType(38, 1, "Blue Orchid", "red_flower"));
		ret.add(new BlockType(38, 2, "Allium", "red_flower"));
		ret.add(new BlockType(38, 3, "Azure Bluet", "red_flower"));
		ret.add(new BlockType(38, 4, "Red Tulip", "red_flower"));
		ret.add(new BlockType(38, 5, "Orange Tulip", "red_flower"));
		ret.add(new BlockType(38, 6, "White Tulip", "red_flower"));
		ret.add(new BlockType(38, 7, "Pink Tulip", "red_flower"));
		ret.add(new BlockType(38, 8, "Oxeye Daisy", "red_flower"));
		ret.add(new BlockType(39, 0, "Brown Mushroom", "brown_mushroom"));
		ret.add(new BlockType(40, 0, "Red Mushroom", "red_mushroom"));
		ret.add(new BlockType(41, 0, "Gold Block", "gold_block"));
		ret.add(new BlockType(42, 0, "Iron Block", "iron_block"));
		ret.add(new BlockType(43, 0, "Double Stone Slab", "double_stone_slab"));
		ret.add(new BlockType(43, 1, "Double Sandstone Slab", "double_stone_slab"));
		ret.add(new BlockType(43, 2, "Double Wooden Slab", "double_stone_slab"));
		ret.add(new BlockType(43, 3, "Double Cobblestone Slab", "double_stone_slab"));
		ret.add(new BlockType(43, 4, "Double Brick Slab", "double_stone_slab"));
		ret.add(new BlockType(43, 5, "Double Stone Brick Slab", "double_stone_slab"));
		ret.add(new BlockType(43, 6, "Double Nether Brick Slab", "double_stone_slab"));
		ret.add(new BlockType(43, 7, "Double Quartz Slab", "double_stone_slab"));
		ret.add(new BlockType(44, 0, "Stone Slab", "stone_slab"));
		ret.add(new BlockType(44, 1, "Sandstone Slab", "stone_slab"));
		ret.add(new BlockType(44, 2, "Wooden Slab", "stone_slab"));
		ret.add(new BlockType(44, 3, "Cobblestone Slab", "stone_slab"));
		ret.add(new BlockType(44, 4, "Brick Slab", "stone_slab"));
		ret.add(new BlockType(44, 5, "Stone Brick Slab", "stone_slab"));
		ret.add(new BlockType(44, 6, "Nether Brick Slab", "stone_slab"));
		ret.add(new BlockType(44, 7, "Quartz Slab", "stone_slab"));
		ret.add(new BlockType(45, 0, "Bricks", "brick_block"));
		ret.add(new BlockType(46, 0, "TNT", "tnt"));
		ret.add(new BlockType(47, 0, "Bookshelf", "bookshelf"));
		ret.add(new BlockType(48, 0, "Moss Stone", "mossy_cobblestone"));
		ret.add(new BlockType(49, 0, "Obsidian", "obsidian"));
		ret.add(new BlockType(50, 0, "Torch", "torch"));
		ret.add(new BlockType(51, 0, "Fire", "fire"));
		ret.add(new BlockType(52, 0, "Monster Spawner", "mob_spawner"));
		ret.add(new BlockType(53, 0, "Oak Wood Stairs", "oak_stairs"));
		ret.add(new BlockType(54, 0, "Chest", "chest"));
		ret.add(new BlockType(55, 0, "Redstone Wire", "redstone_wire"));
		ret.add(new BlockType(56, 0, "Diamond Ore", "diamond_ore"));
		ret.add(new BlockType(57, 0, "Diamond Block", "diamond_block"));
		ret.add(new BlockType(58, 0, "Crafting Table", "crafting_table"));
		ret.add(new BlockType(59, 0, "Wheat Crops", "wheat"));
		ret.add(new BlockType(60, 0, "Farmland", "farmland"));
		ret.add(new BlockType(61, 0, "Furnace", "furnace"));
		ret.add(new BlockType(62, 0, "Burning Furnace", "lit_furnace"));
		ret.add(new BlockType(63, 0, "Standing Sign Block", "standing_sign"));
		ret.add(new BlockType(64, 0, "Oak Door Block", "wooden_door"));
		ret.add(new BlockType(65, 0, "Ladder", "ladder"));
		ret.add(new BlockType(66, 0, "Rail", "rail"));
		ret.add(new BlockType(67, 0, "Cobblestone Stairs", "stone_stairs"));
		ret.add(new BlockType(68, 0, "Wall-mounted Sign Block", "wall_sign"));
		ret.add(new BlockType(69, 0, "Lever", "lever"));
		ret.add(new BlockType(70, 0, "Stone Pressure Plate", "stone_pressure_plate"));
		ret.add(new BlockType(71, 0, "Iron Door Block", "iron_door"));
		ret.add(new BlockType(72, 0, "Wooden Pressure Plate", "wooden_pressure_plate"));
		ret.add(new BlockType(73, 0, "Redstone Ore", "redstone_ore"));
		ret.add(new BlockType(74, 0, "Glowing Redstone Ore", "lit_redstone_ore"));
		ret.add(new BlockType(75, 0, "Redstone Torch (off", "unlit_redstone_torch"));
		ret.add(new BlockType(76, 0, "Redstone Torch (on", "redstone_torch"));
		ret.add(new BlockType(77, 0, "Stone Button", "stone_button"));
		ret.add(new BlockType(78, 0, "Snow", "snow_layer"));
		ret.add(new BlockType(79, 0, "Ice", "ice"));
		ret.add(new BlockType(80, 0, "Snow Block", "snow"));
		ret.add(new BlockType(81, 0, "Cactus", "cactus"));
		ret.add(new BlockType(82, 0, "Clay", "clay"));
		ret.add(new BlockType(83, 0, "Sugar Canes", "reeds"));
		ret.add(new BlockType(84, 0, "Jukebox", "jukebox"));
		ret.add(new BlockType(85, 0, "Oak Fence", "fence"));
		ret.add(new BlockType(86, 0, "Pumpkin", "pumpkin"));
		ret.add(new BlockType(87, 0, "Netherrack", "netherrack"));
		ret.add(new BlockType(88, 0, "Soul Sand", "soul_sand"));
		ret.add(new BlockType(89, 0, "Glowstone", "glowstone"));
		ret.add(new BlockType(90, 0, "Nether Portal", "portal"));
		ret.add(new BlockType(91, 0, "Jack o'Lantern", "lit_pumpkin"));
		ret.add(new BlockType(92, 0, "Cake Block", "cake"));
		ret.add(new BlockType(93, 0, "Redstone Repeater Block (off", "unpowered_repeater"));
		ret.add(new BlockType(94, 0, "Redstone Repeater Block (on", "powered_repeater"));
		ret.add(new BlockType(95, 0, "White Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 1, "Orange Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 2, "Magenta Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 3, "Light Blue Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 4, "Yellow Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 5, "Lime Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 6, "Pink Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 7, "Gray Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 8, "Light Gray Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 9, "Cyan Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 10, "Purple Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 11, "Blue Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 12, "Brown Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 13, "Green Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 14, "Red Stained Glass", "stained_glass"));
		ret.add(new BlockType(95, 15, "Black Stained Glass", "stained_glass"));
		ret.add(new BlockType(96, 0, "Wooden Trapdoor", "trapdoor"));
		ret.add(new BlockType(97, 0, "Stone Monster Egg", "monster_egg"));
		ret.add(new BlockType(97, 1, "Cobblestone Monster Egg", "monster_egg"));
		ret.add(new BlockType(97, 2, "Stone Brick Monster Egg", "monster_egg"));
		ret.add(new BlockType(97, 3, "Mossy Stone Brick Monster Egg", "monster_egg"));
		ret.add(new BlockType(97, 4, "Cracked Stone Brick Monster Egg", "monster_egg"));
		ret.add(new BlockType(97, 5, "Chiseled Stone Brick Monster Egg", "monster_egg"));
		ret.add(new BlockType(98, 0, "Stone Bricks", "stonebrick"));
		ret.add(new BlockType(98, 1, "Mossy Stone Bricks", "stonebrick"));
		ret.add(new BlockType(98, 2, "Cracked Stone Bricks", "stonebrick"));
		ret.add(new BlockType(98, 3, "Chiseled Stone Bricks", "stonebrick"));
		ret.add(new BlockType(99, 0, "Brown Mushroom Block", "brown_mushroom_block"));
		ret.add(new BlockType(100, 0, "Red Mushroom Block", "red_mushroom_block"));
		ret.add(new BlockType(101, 0, "Iron Bars", "iron_bars"));
		ret.add(new BlockType(102, 0, "Glass Pane", "glass_pane"));
		ret.add(new BlockType(103, 0, "Melon Block", "melon_block"));
		ret.add(new BlockType(104, 0, "Pumpkin Stem", "pumpkin_stem"));
		ret.add(new BlockType(105, 0, "Melon Stem", "melon_stem"));
		ret.add(new BlockType(106, 0, "Vines", "vine"));
		ret.add(new BlockType(107, 0, "Oak Fence Gate", "fence_gate"));
		ret.add(new BlockType(108, 0, "Brick Stairs", "brick_stairs"));
		ret.add(new BlockType(109, 0, "Stone Brick Stairs", "stone_brick_stairs"));
		ret.add(new BlockType(110, 0, "Mycelium", "mycelium"));
		ret.add(new BlockType(111, 0, "Lily Pad", "waterlily"));
		ret.add(new BlockType(112, 0, "Nether Brick", "nether_brick"));
		ret.add(new BlockType(113, 0, "Nether Brick Fence", "nether_brick_fence"));
		ret.add(new BlockType(114, 0, "Nether Brick Stairs", "nether_brick_stairs"));
		ret.add(new BlockType(115, 0, "Nether Wart", "nether_wart"));
		ret.add(new BlockType(116, 0, "Enchantment Table", "enchanting_table"));
		ret.add(new BlockType(117, 0, "Brewing Stand", "brewing_stand"));
		ret.add(new BlockType(118, 0, "Cauldron", "cauldron"));
		ret.add(new BlockType(119, 0, "End Portal", "end_portal"));
		ret.add(new BlockType(120, 0, "End Portal Frame", "end_portal_frame"));
		ret.add(new BlockType(121, 0, "End Stone", "end_stone"));
		ret.add(new BlockType(122, 0, "Dragon Egg", "dragon_egg"));
		ret.add(new BlockType(123, 0, "Redstone Lamp (inactive", "redstone_lamp"));
		ret.add(new BlockType(124, 0, "Redstone Lamp (active", "lit_redstone_lamp"));
		ret.add(new BlockType(125, 0, "Double Oak Wood Slab", "double_wooden_slab"));
		ret.add(new BlockType(125, 1, "Double Spruce Wood Slab", "double_wooden_slab"));
		ret.add(new BlockType(125, 2, "Double Birch Wood Slab", "double_wooden_slab"));
		ret.add(new BlockType(125, 3, "Double Jungle Wood Slab", "double_wooden_slab"));
		ret.add(new BlockType(125, 4, "Double Acacia Wood Slab", "double_wooden_slab"));
		ret.add(new BlockType(125, 5, "Double Dark Oak Wood Slab", "double_wooden_slab"));
		ret.add(new BlockType(126, 0, "Oak Wood Slab", "wooden_slab"));
		ret.add(new BlockType(126, 1, "Spruce Wood Slab", "wooden_slab"));
		ret.add(new BlockType(126, 2, "Birch Wood Slab", "wooden_slab"));
		ret.add(new BlockType(126, 3, "Jungle Wood Slab", "wooden_slab"));
		ret.add(new BlockType(126, 4, "Acacia Wood Slab", "wooden_slab"));
		ret.add(new BlockType(126, 5, "Dark Oak Wood Slab", "wooden_slab"));
		ret.add(new BlockType(127, 0, "Cocoa", "cocoa"));
		ret.add(new BlockType(128, 0, "Sandstone Stairs", "sandstone_stairs"));
		ret.add(new BlockType(129, 0, "Emerald Ore", "emerald_ore"));
		ret.add(new BlockType(130, 0, "Ender Chest", "ender_chest"));
		ret.add(new BlockType(131, 0, "Tripwire Hook", "tripwire_hook"));
		ret.add(new BlockType(132, 0, "Tripwire", "tripwire_hook"));
		ret.add(new BlockType(133, 0, "Emerald Block", "emerald_block"));
		ret.add(new BlockType(134, 0, "Spruce Wood Stairs", "spruce_stairs"));
		ret.add(new BlockType(135, 0, "Birch Wood Stairs", "birch_stairs"));
		ret.add(new BlockType(136, 0, "Jungle Wood Stairs", "jungle_stairs"));
		ret.add(new BlockType(137, 0, "Command Block", "command_block"));
		ret.add(new BlockType(138, 0, "Beacon", "beacon"));
		ret.add(new BlockType(139, 0, "Cobblestone Wall", "cobblestone_wall"));
		ret.add(new BlockType(139, 1, "Mossy Cobblestone Wall", "cobblestone_wall"));
		ret.add(new BlockType(140, 0, "Flower Pot", "flower_pot"));
		ret.add(new BlockType(141, 0, "Carrots", "carrots"));
		ret.add(new BlockType(142, 0, "Potatoes", "potatoes"));
		ret.add(new BlockType(143, 0, "Wooden Button", "wooden_button"));
		ret.add(new BlockType(144, 0, "Mob Head", "skull"));
		ret.add(new BlockType(145, 0, "Anvil", "anvil"));
		ret.add(new BlockType(146, 0, "Trapped Chest", "trapped_chest"));
		ret.add(new BlockType(147, 0, "Weighted Pressure Plate (light", "light_weighted_pressure_plate"));
		ret.add(new BlockType(148, 0, "Weighted Pressure Plate (heavy", "heavy_weighted_pressure_plate"));
		ret.add(new BlockType(149, 0, "Redstone Comparator (inactive", "unpowered_comparator"));
		ret.add(new BlockType(150, 0, "Redstone Comparator (active", "powered_comparator"));
		ret.add(new BlockType(151, 0, "Daylight Sensor", "daylight_detector"));
		ret.add(new BlockType(152, 0, "Redstone Block", "redstone_block"));
		ret.add(new BlockType(153, 0, "Nether Quartz Ore", "quartz_ore"));
		ret.add(new BlockType(154, 0, "Hopper", "hopper"));
		ret.add(new BlockType(155, 0, "Quartz Block", "quartz_block"));
		ret.add(new BlockType(155, 1, "Chiseled Quartz Block", "quartz_block"));
		ret.add(new BlockType(155, 2, "Pillar Quartz Block", "quartz_block"));
		ret.add(new BlockType(156, 0, "Quartz Stairs", "quartz_stairs"));
		ret.add(new BlockType(157, 0, "Activator Rail", "activator_rail"));
		ret.add(new BlockType(158, 0, "Dropper", "dropper"));
		ret.add(new BlockType(159, 0, "White Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 1, "Orange Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 2, "Magenta Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 3, "Light Blue Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 4, "Yellow Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 5, "Lime Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 6, "Pink Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 7, "Gray Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 8, "Light Gray Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 9, "Cyan Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 10, "Purple Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 11, "Blue Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 12, "Brown Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 13, "Green Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 14, "Red Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(159, 15, "Black Stained Clay", "stained_hardened_clay"));
		ret.add(new BlockType(160, 0, "White Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 1, "Orange Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 2, "Magenta Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 3, "Light Blue Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 4, "Yellow Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 5, "Lime Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 6, "Pink Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 7, "Gray Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 8, "Light Gray Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 9, "Cyan Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 10, "Purple Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 11, "Blue Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 12, "Brown Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 13, "Green Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 14, "Red Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(160, 15, "Black Stained Glass Pane", "stained_glass_pane"));
		ret.add(new BlockType(161, 0, "Acacia Leaves", "leaves2"));
		ret.add(new BlockType(161, 1, "Dark Oak Leaves", "leaves2"));
		ret.add(new BlockType(162, 0, "Acacia Wood", "log2"));
		ret.add(new BlockType(162, 1, "Dark Oak Wood", "log2"));
		ret.add(new BlockType(163, 0, "Acacia Wood Stairs", "acacia_stairs"));
		ret.add(new BlockType(164, 0, "Dark Oak Wood Stairs", "dark_oak_stairs"));
		ret.add(new BlockType(165, 0, "Slime Block", "slime"));
		ret.add(new BlockType(166, 0, "Barrier", "barrier"));
		ret.add(new BlockType(167, 0, "Iron Trapdoor", "iron_trapdoor"));
		ret.add(new BlockType(168, 0, "Prismarine", "prismarine"));
		ret.add(new BlockType(168, 1, "Prismarine Bricks", "prismarine"));
		ret.add(new BlockType(168, 2, "Dark Prismarine", "prismarine"));
		ret.add(new BlockType(169, 0, "Sea Lantern", "sea_lantern"));
		ret.add(new BlockType(170, 0, "Hay Bale", "hay_block"));
		ret.add(new BlockType(171, 0, "White Carpet", "carpet"));
		ret.add(new BlockType(171, 1, "Orange Carpet", "carpet"));
		ret.add(new BlockType(171, 2, "Magenta Carpet", "carpet"));
		ret.add(new BlockType(171, 3, "Light Blue Carpet", "carpet"));
		ret.add(new BlockType(171, 4, "Yellow Carpet", "carpet"));
		ret.add(new BlockType(171, 5, "Lime Carpet", "carpet"));
		ret.add(new BlockType(171, 6, "Pink Carpet", "carpet"));
		ret.add(new BlockType(171, 7, "Gray Carpet", "carpet"));
		ret.add(new BlockType(171, 8, "Light Gray Carpet", "carpet"));
		ret.add(new BlockType(171, 9, "Cyan Carpet", "carpet"));
		ret.add(new BlockType(171, 10, "Purple Carpet", "carpet"));
		ret.add(new BlockType(171, 11, "Blue Carpet", "carpet"));
		ret.add(new BlockType(171, 12, "Brown Carpet", "carpet"));
		ret.add(new BlockType(171, 13, "Green Carpet", "carpet"));
		ret.add(new BlockType(171, 14, "Red Carpet", "carpet"));
		ret.add(new BlockType(171, 15, "Black Carpet", "carpet"));
		ret.add(new BlockType(172, 0, "Hardened Clay", "hardened_clay"));
		ret.add(new BlockType(173, 0, "Block of Coal", "coal_block"));
		ret.add(new BlockType(174, 0, "Packed Ice", "packed_ice"));
		ret.add(new BlockType(175, 0, "Sunflower", "double_plant"));
		ret.add(new BlockType(175, 1, "Lilac", "double_plant"));
		ret.add(new BlockType(175, 2, "Double Tallgrass", "double_plant"));
		ret.add(new BlockType(175, 3, "Large Fern", "double_plant"));
		ret.add(new BlockType(175, 4, "Rose Bush", "double_plant"));
		ret.add(new BlockType(175, 5, "Peony", "double_plant"));
		ret.add(new BlockType(176, 0, "Free-standing Banner", "standing_banner"));
		ret.add(new BlockType(177, 0, "Wall-mounted Banner", "wall_banner"));
		ret.add(new BlockType(178, 0, "Inverted Daylight Sensor", "daylight_detector_inverted"));
		ret.add(new BlockType(179, 0, "Red Sandstone", "red_sandstone"));
		ret.add(new BlockType(179, 1, "Chiseled Red Sandstone", "red_sandstone"));
		ret.add(new BlockType(179, 2, "Smooth Red Sandstone", "red_sandstone"));
		ret.add(new BlockType(180, 0, "Red Sandstone Stairs", "red_sandstone_stairs"));
		ret.add(new BlockType(181, 0, "Double Red Sandstone Slab", "stone_slab2"));
		ret.add(new BlockType(182, 0, "Red Sandstone Slab", "double_stone_slab2"));
		ret.add(new BlockType(183, 0, "Spruce Fence Gate", "spruce_fence_gate"));
		ret.add(new BlockType(184, 0, "Birch Fence Gate", "birch_fence_gate"));
		ret.add(new BlockType(185, 0, "Jungle Fence Gate", "jungle_fence_gate"));
		ret.add(new BlockType(186, 0, "Dark Oak Fence Gate", "dark_oak_fence_gate"));
		ret.add(new BlockType(187, 0, "Acacia Fence Gate", "acacia_fence_gate"));
		ret.add(new BlockType(188, 0, "Spruce Fence", "spruce_fence"));
		ret.add(new BlockType(189, 0, "Birch Fence", "birch_fence"));
		ret.add(new BlockType(190, 0, "Jungle Fence", "jungle_fence"));
		ret.add(new BlockType(191, 0, "Dark Oak Fence", "dark_oak_fence"));
		ret.add(new BlockType(192, 0, "Acacia Fence", "acacia_fence"));
		ret.add(new BlockType(193, 0, "Spruce Door Block", "spruce_door"));
		ret.add(new BlockType(194, 0, "Birch Door Block", "birch_door"));
		ret.add(new BlockType(195, 0, "Jungle Door Block", "jungle_door"));
		ret.add(new BlockType(196, 0, "Acacia Door Block", "acacia_door"));
		ret.add(new BlockType(197, 0, "Dark Oak Door Block", "dark_oak_door"));
		return ret;
	}

	public static BlockType findBlock(int id, int metadata)
	{
		if (id < 0) id = 256 + id;
		for (BlockType block : BlockResources.blocks)
		{
			if (block.id == id && block.metadata == metadata) return block;
		}
		return new BlockType(id, metadata, "unknown_id_" + id, "unknown_id_" + id);
	}

	public static BlockType generateUnknown(int id, int metadata)
	{
		if (id < 0) id = 256 + id;
		return new BlockType(id, metadata, "unknown_id_" + id, "unknown_id_" + id);
	}

	public static BlockType findBlock(int id)
	{
		return findBlock(id, 0);
	}
}
